2021-09-22 19:10:14,575 INFO    MainThread:124810 [wandb_setup.py:_flush():69] setting env: {}
2021-09-22 19:10:14,575 INFO    MainThread:124810 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-22 19:10:14,575 INFO    MainThread:124810 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20210922_191014-3s2b7p5y/logs/debug.log
2021-09-22 19:10:14,575 INFO    MainThread:124810 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20210922_191014-3s2b7p5y/logs/debug-internal.log
2021-09-22 19:10:14,575 INFO    MainThread:124810 [wandb_init.py:init():381] calling init triggers
2021-09-22 19:10:14,575 INFO    MainThread:124810 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-09-22 19:10:14,575 INFO    MainThread:124810 [wandb_init.py:init():430] starting backend
2021-09-22 19:10:14,575 INFO    MainThread:124810 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-22 19:10:14,579 INFO    MainThread:124810 [backend.py:ensure_launched():135] starting backend process...
2021-09-22 19:10:14,591 INFO    MainThread:124810 [backend.py:ensure_launched():140] started backend process with pid: 124964
2021-09-22 19:10:14,593 INFO    MainThread:124810 [wandb_init.py:init():435] backend started and connected
2021-09-22 19:10:14,595 INFO    MainThread:124810 [wandb_init.py:init():494] updated telemetry
2021-09-22 19:10:14,595 INFO    MainThread:124810 [wandb_init.py:init():517] communicating current version
2021-09-22 19:10:15,245 INFO    MainThread:124810 [wandb_init.py:init():522] got version response 
2021-09-22 19:10:15,246 INFO    MainThread:124810 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-22 19:10:15,391 INFO    MainThread:124810 [wandb_init.py:init():557] starting run threads in backend
2021-09-22 19:10:19,918 INFO    MainThread:124810 [wandb_run.py:_console_start():1605] atexit reg
2021-09-22 19:10:19,919 INFO    MainThread:124810 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-09-22 19:10:19,919 INFO    MainThread:124810 [wandb_run.py:_redirect():1484] Redirecting console.
2021-09-22 19:10:19,922 INFO    MainThread:124810 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-22 19:10:19,922 INFO    MainThread:124810 [wandb_init.py:init():582] run started, returning control to user process
2021-09-22 21:01:34,160 INFO    MainThread:124810 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 255
2021-09-22 21:01:34,160 INFO    MainThread:124810 [wandb_run.py:_restore():1547] restore
2021-09-22 21:01:36,405 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-22 21:01:36,658 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-22 21:01:36,777 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-22 21:01:36,880 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 12327
}

2021-09-22 21:01:36,982 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12327
  total_bytes: 12327
}

2021-09-22 21:01:37,085 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12327
  total_bytes: 12327
}

2021-09-22 21:01:37,187 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12327
  total_bytes: 12327
}

2021-09-22 21:01:37,290 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12327
  total_bytes: 12327
}

2021-09-22 21:01:37,392 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12327
  total_bytes: 12327
}

2021-09-22 21:01:37,604 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12327
  total_bytes: 12327
}

2021-09-22 21:01:37,882 INFO    MainThread:124810 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12327
  total_bytes: 12327
}
local_info {
}

2021-09-22 21:01:39,163 INFO    MainThread:124810 [wandb_run.py:_show_files():1947] logging synced files
