2021-11-02 21:15:45,739 INFO    MainThread:22483 [wandb_setup.py:_flush():69] setting env: {}
2021-11-02 21:15:45,739 INFO    MainThread:22483 [wandb_setup.py:_flush():69] setting login settings: {}
2021-11-02 21:15:45,740 INFO    MainThread:22483 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20211102_211545-1qb59hdo/logs/debug.log
2021-11-02 21:15:45,740 INFO    MainThread:22483 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20211102_211545-1qb59hdo/logs/debug-internal.log
2021-11-02 21:15:45,740 INFO    MainThread:22483 [wandb_init.py:init():381] calling init triggers
2021-11-02 21:15:45,740 INFO    MainThread:22483 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-11-02 21:15:45,740 INFO    MainThread:22483 [wandb_init.py:init():430] starting backend
2021-11-02 21:15:45,740 INFO    MainThread:22483 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-02 21:15:45,850 INFO    MainThread:22483 [backend.py:ensure_launched():135] starting backend process...
2021-11-02 21:15:45,929 INFO    MainThread:22483 [backend.py:ensure_launched():140] started backend process with pid: 23872
2021-11-02 21:15:45,931 INFO    MainThread:22483 [wandb_init.py:init():435] backend started and connected
2021-11-02 21:15:45,933 INFO    MainThread:22483 [wandb_init.py:init():494] updated telemetry
2021-11-02 21:15:45,934 INFO    MainThread:22483 [wandb_init.py:init():517] communicating current version
2021-11-02 21:15:47,015 INFO    MainThread:22483 [wandb_init.py:init():522] got version response upgrade_message: "wandb version 0.12.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-11-02 21:15:47,018 INFO    MainThread:22483 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-11-02 21:15:47,172 INFO    MainThread:22483 [wandb_init.py:init():557] starting run threads in backend
2021-11-02 21:15:52,180 INFO    MainThread:22483 [wandb_run.py:_console_start():1605] atexit reg
2021-11-02 21:15:52,180 INFO    MainThread:22483 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-11-02 21:15:52,181 INFO    MainThread:22483 [wandb_run.py:_redirect():1484] Redirecting console.
2021-11-02 21:15:52,187 INFO    MainThread:22483 [wandb_run.py:_redirect():1540] Redirects installed.
2021-11-02 21:15:52,187 INFO    MainThread:22483 [wandb_init.py:init():582] run started, returning control to user process
2021-11-02 23:42:39,350 INFO    MainThread:22483 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 255
2021-11-02 23:42:39,351 INFO    MainThread:22483 [wandb_run.py:_restore():1547] restore
2021-11-02 23:42:41,664 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-11-02 23:42:42,170 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-11-02 23:42:42,305 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-11-02 23:42:42,841 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 437912
}

2021-11-02 23:42:42,945 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 438323
}

2021-11-02 23:42:43,054 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 36813
  total_bytes: 438323
}

2021-11-02 23:42:43,158 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 438323
  total_bytes: 438323
}

2021-11-02 23:42:43,261 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 438323
  total_bytes: 438323
}

2021-11-02 23:42:43,369 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 438323
  total_bytes: 438323
}

2021-11-02 23:42:43,472 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 438323
  total_bytes: 438323
}

2021-11-02 23:42:43,698 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 438323
  total_bytes: 438323
}

2021-11-02 23:42:43,975 INFO    MainThread:22483 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 438323
  total_bytes: 438323
}
local_info {
}

2021-11-02 23:42:45,293 INFO    MainThread:22483 [wandb_run.py:_show_summary():1853] rendering summary
2021-11-02 23:42:45,295 INFO    MainThread:22483 [wandb_run.py:_show_history():1898] rendering history
2021-11-02 23:42:45,299 INFO    MainThread:22483 [wandb_run.py:_show_files():1947] logging synced files
