2021-11-02 23:50:53,375 INFO    MainThread:33518 [wandb_setup.py:_flush():69] setting env: {}
2021-11-02 23:50:53,375 INFO    MainThread:33518 [wandb_setup.py:_flush():69] setting login settings: {}
2021-11-02 23:50:53,375 INFO    MainThread:33518 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20211102_235053-2tgdcmox/logs/debug.log
2021-11-02 23:50:53,375 INFO    MainThread:33518 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20211102_235053-2tgdcmox/logs/debug-internal.log
2021-11-02 23:50:53,375 INFO    MainThread:33518 [wandb_init.py:init():381] calling init triggers
2021-11-02 23:50:53,375 INFO    MainThread:33518 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-11-02 23:50:53,376 INFO    MainThread:33518 [wandb_init.py:init():430] starting backend
2021-11-02 23:50:53,376 INFO    MainThread:33518 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-02 23:50:53,447 INFO    MainThread:33518 [backend.py:ensure_launched():135] starting backend process...
2021-11-02 23:50:53,525 INFO    MainThread:33518 [backend.py:ensure_launched():140] started backend process with pid: 34517
2021-11-02 23:50:53,527 INFO    MainThread:33518 [wandb_init.py:init():435] backend started and connected
2021-11-02 23:50:53,529 INFO    MainThread:33518 [wandb_init.py:init():494] updated telemetry
2021-11-02 23:50:53,532 INFO    MainThread:33518 [wandb_init.py:init():517] communicating current version
2021-11-02 23:50:54,459 INFO    MainThread:33518 [wandb_init.py:init():522] got version response upgrade_message: "wandb version 0.12.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-11-02 23:50:54,460 INFO    MainThread:33518 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-11-02 23:50:54,611 INFO    MainThread:33518 [wandb_init.py:init():557] starting run threads in backend
2021-11-02 23:50:59,620 INFO    MainThread:33518 [wandb_run.py:_console_start():1605] atexit reg
2021-11-02 23:50:59,620 INFO    MainThread:33518 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-11-02 23:50:59,621 INFO    MainThread:33518 [wandb_run.py:_redirect():1484] Redirecting console.
2021-11-02 23:50:59,624 INFO    MainThread:33518 [wandb_run.py:_redirect():1540] Redirects installed.
2021-11-02 23:50:59,624 INFO    MainThread:33518 [wandb_init.py:init():582] run started, returning control to user process
2021-11-02 23:51:08,017 INFO    MainThread:33518 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 1
2021-11-02 23:51:08,018 INFO    MainThread:33518 [wandb_run.py:_restore():1547] restore
2021-11-02 23:51:10,723 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-11-02 23:51:11,239 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-11-02 23:51:11,380 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-11-02 23:51:11,664 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 10092
}

2021-11-02 23:51:11,767 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 10503
}

2021-11-02 23:51:11,871 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10503
  total_bytes: 10503
}

2021-11-02 23:51:11,974 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10503
  total_bytes: 10503
}

2021-11-02 23:51:12,080 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10503
  total_bytes: 10503
}

2021-11-02 23:51:12,184 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10503
  total_bytes: 10503
}

2021-11-02 23:51:12,441 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10503
  total_bytes: 10503
}

2021-11-02 23:51:12,706 INFO    MainThread:33518 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10503
  total_bytes: 10503
}
local_info {
}

2021-11-02 23:51:14,114 INFO    MainThread:33518 [wandb_run.py:_show_files():1947] logging synced files
