2021-09-22 21:50:48,519 INFO    MainThread:114448 [wandb_setup.py:_flush():69] setting env: {}
2021-09-22 21:50:48,519 INFO    MainThread:114448 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-22 21:50:48,519 INFO    MainThread:114448 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20210922_215048-19t2t1au/logs/debug.log
2021-09-22 21:50:48,519 INFO    MainThread:114448 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20210922_215048-19t2t1au/logs/debug-internal.log
2021-09-22 21:50:48,519 INFO    MainThread:114448 [wandb_init.py:init():381] calling init triggers
2021-09-22 21:50:48,519 INFO    MainThread:114448 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-09-22 21:50:48,519 INFO    MainThread:114448 [wandb_init.py:init():430] starting backend
2021-09-22 21:50:48,519 INFO    MainThread:114448 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-22 21:50:48,523 INFO    MainThread:114448 [backend.py:ensure_launched():135] starting backend process...
2021-09-22 21:50:48,595 INFO    MainThread:114448 [backend.py:ensure_launched():140] started backend process with pid: 114953
2021-09-22 21:50:48,597 INFO    MainThread:114448 [wandb_init.py:init():435] backend started and connected
2021-09-22 21:50:48,598 INFO    MainThread:114448 [wandb_init.py:init():494] updated telemetry
2021-09-22 21:50:48,599 INFO    MainThread:114448 [wandb_init.py:init():517] communicating current version
2021-09-22 21:50:49,325 INFO    MainThread:114448 [wandb_init.py:init():522] got version response 
2021-09-22 21:50:49,325 INFO    MainThread:114448 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-22 21:50:49,465 INFO    MainThread:114448 [wandb_init.py:init():557] starting run threads in backend
2021-09-22 21:50:53,776 INFO    MainThread:114448 [wandb_run.py:_console_start():1605] atexit reg
2021-09-22 21:50:53,777 INFO    MainThread:114448 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-09-22 21:50:53,777 INFO    MainThread:114448 [wandb_run.py:_redirect():1484] Redirecting console.
2021-09-22 21:50:53,781 INFO    MainThread:114448 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-22 21:50:53,781 INFO    MainThread:114448 [wandb_init.py:init():582] run started, returning control to user process
2021-09-22 21:51:05,718 INFO    MainThread:114448 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 255
2021-09-22 21:51:05,718 INFO    MainThread:114448 [wandb_run.py:_restore():1547] restore
2021-09-22 21:51:07,850 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-22 21:51:08,124 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-22 21:51:08,244 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-22 21:51:08,510 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 15847
}

2021-09-22 21:51:08,613 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 16256
}

2021-09-22 21:51:08,716 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16256
  total_bytes: 16256
}

2021-09-22 21:51:08,818 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16256
  total_bytes: 16256
}

2021-09-22 21:51:08,921 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16256
  total_bytes: 16256
}

2021-09-22 21:51:09,024 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16256
  total_bytes: 16256
}

2021-09-22 21:51:09,281 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16256
  total_bytes: 16256
}

2021-09-22 21:51:09,548 INFO    MainThread:114448 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16256
  total_bytes: 16256
}
local_info {
}

2021-09-22 21:51:10,794 INFO    MainThread:114448 [wandb_run.py:_show_files():1947] logging synced files
