2021-09-16 23:14:44,696 INFO    MainThread:38139 [wandb_setup.py:_flush():69] setting env: {}
2021-09-16 23:14:44,696 INFO    MainThread:38139 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-16 23:14:44,697 INFO    MainThread:38139 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20210916_231444-70zhys1g/logs/debug.log
2021-09-16 23:14:44,697 INFO    MainThread:38139 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20210916_231444-70zhys1g/logs/debug-internal.log
2021-09-16 23:14:44,697 INFO    MainThread:38139 [wandb_init.py:init():381] calling init triggers
2021-09-16 23:14:44,697 INFO    MainThread:38139 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-09-16 23:14:44,697 INFO    MainThread:38139 [wandb_init.py:init():430] starting backend
2021-09-16 23:14:44,697 INFO    MainThread:38139 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-16 23:14:44,702 INFO    MainThread:38139 [backend.py:ensure_launched():135] starting backend process...
2021-09-16 23:14:44,716 INFO    MainThread:38139 [backend.py:ensure_launched():140] started backend process with pid: 38255
2021-09-16 23:14:44,717 INFO    MainThread:38139 [wandb_init.py:init():435] backend started and connected
2021-09-16 23:14:44,721 INFO    MainThread:38139 [wandb_init.py:init():494] updated telemetry
2021-09-16 23:14:44,722 INFO    MainThread:38139 [wandb_init.py:init():517] communicating current version
2021-09-16 23:14:45,577 INFO    MainThread:38139 [wandb_init.py:init():522] got version response 
2021-09-16 23:14:45,578 INFO    MainThread:38139 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-16 23:14:45,721 INFO    MainThread:38139 [wandb_init.py:init():557] starting run threads in backend
2021-09-16 23:14:50,728 INFO    MainThread:38139 [wandb_run.py:_console_start():1605] atexit reg
2021-09-16 23:14:50,728 INFO    MainThread:38139 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-09-16 23:14:50,729 INFO    MainThread:38139 [wandb_run.py:_redirect():1484] Redirecting console.
2021-09-16 23:14:50,732 INFO    MainThread:38139 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-16 23:14:50,732 INFO    MainThread:38139 [wandb_init.py:init():582] run started, returning control to user process
2021-09-16 23:15:00,732 INFO    MainThread:38139 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-16 23:15:00,733 INFO    MainThread:38139 [wandb_run.py:_restore():1547] restore
2021-09-16 23:15:02,791 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-16 23:15:03,177 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-16 23:15:03,300 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-16 23:15:03,768 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 9926
}

2021-09-16 23:15:03,871 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 10335
}

2021-09-16 23:15:03,974 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10335
  total_bytes: 10335
}

2021-09-16 23:15:04,076 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10335
  total_bytes: 10335
}

2021-09-16 23:15:04,179 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10335
  total_bytes: 10335
}

2021-09-16 23:15:04,282 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10335
  total_bytes: 10335
}

2021-09-16 23:15:04,538 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10335
  total_bytes: 10335
}

2021-09-16 23:15:04,830 INFO    MainThread:38139 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10335
  total_bytes: 10335
}
local_info {
}

2021-09-16 23:15:06,257 INFO    MainThread:38139 [wandb_run.py:_show_files():1947] logging synced files
