2021-10-02 12:03:53,235 INFO    MainThread:34920 [wandb_setup.py:_flush():69] setting env: {}
2021-10-02 12:03:53,235 INFO    MainThread:34920 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-02 12:03:53,235 INFO    MainThread:34920 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20211002_120353-18jm1dx2/logs/debug.log
2021-10-02 12:03:53,235 INFO    MainThread:34920 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20211002_120353-18jm1dx2/logs/debug-internal.log
2021-10-02 12:03:53,235 INFO    MainThread:34920 [wandb_init.py:init():381] calling init triggers
2021-10-02 12:03:53,236 INFO    MainThread:34920 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-10-02 12:03:53,236 INFO    MainThread:34920 [wandb_init.py:init():430] starting backend
2021-10-02 12:03:53,236 INFO    MainThread:34920 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-02 12:03:53,245 INFO    MainThread:34920 [backend.py:ensure_launched():135] starting backend process...
2021-10-02 12:03:53,306 INFO    MainThread:34920 [backend.py:ensure_launched():140] started backend process with pid: 36048
2021-10-02 12:03:53,309 INFO    MainThread:34920 [wandb_init.py:init():435] backend started and connected
2021-10-02 12:03:53,311 INFO    MainThread:34920 [wandb_init.py:init():494] updated telemetry
2021-10-02 12:03:53,312 INFO    MainThread:34920 [wandb_init.py:init():517] communicating current version
2021-10-02 12:03:54,461 INFO    MainThread:34920 [wandb_init.py:init():522] got version response upgrade_message: "wandb version 0.12.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-02 12:03:54,461 INFO    MainThread:34920 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-10-02 12:03:54,610 INFO    MainThread:34920 [wandb_init.py:init():557] starting run threads in backend
2021-10-02 12:03:59,615 INFO    MainThread:34920 [wandb_run.py:_console_start():1605] atexit reg
2021-10-02 12:03:59,616 INFO    MainThread:34920 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-10-02 12:03:59,616 INFO    MainThread:34920 [wandb_run.py:_redirect():1484] Redirecting console.
2021-10-02 12:03:59,619 INFO    MainThread:34920 [wandb_run.py:_redirect():1540] Redirects installed.
2021-10-02 12:03:59,619 INFO    MainThread:34920 [wandb_init.py:init():582] run started, returning control to user process
2021-10-02 12:04:12,538 INFO    MainThread:34920 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 1
2021-10-02 12:04:12,539 INFO    MainThread:34920 [wandb_run.py:_restore():1547] restore
2021-10-02 12:04:14,666 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-10-02 12:04:15,366 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-10-02 12:04:15,488 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-10-02 12:04:15,671 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 12600
}

2021-10-02 12:04:15,773 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 12600
}

2021-10-02 12:04:15,876 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12600
  total_bytes: 12600
}

2021-10-02 12:04:15,978 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12600
  total_bytes: 12600
}

2021-10-02 12:04:16,080 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12600
  total_bytes: 12600
}

2021-10-02 12:04:16,183 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12600
  total_bytes: 12600
}

2021-10-02 12:04:16,285 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12600
  total_bytes: 12600
}

2021-10-02 12:04:16,567 INFO    MainThread:34920 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12600
  total_bytes: 12600
}
local_info {
}

2021-10-02 12:04:17,928 INFO    MainThread:34920 [wandb_run.py:_show_files():1947] logging synced files
