2021-10-08 12:50:19,995 INFO    MainThread:16385 [wandb_setup.py:_flush():69] setting env: {}
2021-10-08 12:50:19,995 INFO    MainThread:16385 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-08 12:50:19,995 INFO    MainThread:16385 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20211008_125019-35ca9faf/logs/debug.log
2021-10-08 12:50:19,996 INFO    MainThread:16385 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20211008_125019-35ca9faf/logs/debug-internal.log
2021-10-08 12:50:19,996 INFO    MainThread:16385 [wandb_init.py:init():381] calling init triggers
2021-10-08 12:50:19,996 INFO    MainThread:16385 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-10-08 12:50:19,996 INFO    MainThread:16385 [wandb_init.py:init():430] starting backend
2021-10-08 12:50:19,996 INFO    MainThread:16385 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-08 12:50:20,038 INFO    MainThread:16385 [backend.py:ensure_launched():135] starting backend process...
2021-10-08 12:50:20,081 INFO    MainThread:16385 [backend.py:ensure_launched():140] started backend process with pid: 16686
2021-10-08 12:50:20,082 INFO    MainThread:16385 [wandb_init.py:init():435] backend started and connected
2021-10-08 12:50:20,085 INFO    MainThread:16385 [wandb_init.py:init():494] updated telemetry
2021-10-08 12:50:20,085 INFO    MainThread:16385 [wandb_init.py:init():517] communicating current version
2021-10-08 12:50:20,867 INFO    MainThread:16385 [wandb_init.py:init():522] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-08 12:50:20,867 INFO    MainThread:16385 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-10-08 12:50:21,017 INFO    MainThread:16385 [wandb_init.py:init():557] starting run threads in backend
2021-10-08 12:50:25,743 INFO    MainThread:16385 [wandb_run.py:_console_start():1605] atexit reg
2021-10-08 12:50:25,744 INFO    MainThread:16385 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-10-08 12:50:25,745 INFO    MainThread:16385 [wandb_run.py:_redirect():1484] Redirecting console.
2021-10-08 12:50:25,748 INFO    MainThread:16385 [wandb_run.py:_redirect():1540] Redirects installed.
2021-10-08 12:50:25,748 INFO    MainThread:16385 [wandb_init.py:init():582] run started, returning control to user process
2021-10-08 12:50:30,504 INFO    MainThread:16385 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 1
2021-10-08 12:50:30,505 INFO    MainThread:16385 [wandb_run.py:_restore():1547] restore
2021-10-08 12:50:32,901 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 739
  total_bytes: 739
}

2021-10-08 12:50:33,120 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 739
  total_bytes: 739
}

2021-10-08 12:50:33,247 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 739
  total_bytes: 739
}

2021-10-08 12:50:34,062 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 739
  total_bytes: 12514
}

2021-10-08 12:50:34,176 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 739
  total_bytes: 12514
}

2021-10-08 12:50:34,279 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12514
  total_bytes: 12514
}

2021-10-08 12:50:34,381 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12514
  total_bytes: 12514
}

2021-10-08 12:50:34,484 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12514
  total_bytes: 12514
}

2021-10-08 12:50:34,586 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12514
  total_bytes: 12514
}

2021-10-08 12:50:34,720 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12514
  total_bytes: 12514
}

2021-10-08 12:50:34,997 INFO    MainThread:16385 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12514
  total_bytes: 12514
}
local_info {
}

2021-10-08 12:50:36,211 INFO    MainThread:16385 [wandb_run.py:_show_files():1947] logging synced files
