2021-09-29 17:40:20,041 INFO    MainThread:50058 [wandb_setup.py:_flush():69] setting env: {}
2021-09-29 17:40:20,041 INFO    MainThread:50058 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-29 17:40:20,042 INFO    MainThread:50058 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20210929_174020-34w472q1/logs/debug.log
2021-09-29 17:40:20,042 INFO    MainThread:50058 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20210929_174020-34w472q1/logs/debug-internal.log
2021-09-29 17:40:20,042 INFO    MainThread:50058 [wandb_init.py:init():381] calling init triggers
2021-09-29 17:40:20,042 INFO    MainThread:50058 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-09-29 17:40:20,042 INFO    MainThread:50058 [wandb_init.py:init():430] starting backend
2021-09-29 17:40:20,042 INFO    MainThread:50058 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-29 17:40:20,049 INFO    MainThread:50058 [backend.py:ensure_launched():135] starting backend process...
2021-09-29 17:40:20,142 INFO    MainThread:50058 [backend.py:ensure_launched():140] started backend process with pid: 54047
2021-09-29 17:40:20,147 INFO    MainThread:50058 [wandb_init.py:init():435] backend started and connected
2021-09-29 17:40:20,149 INFO    MainThread:50058 [wandb_init.py:init():494] updated telemetry
2021-09-29 17:40:20,152 INFO    MainThread:50058 [wandb_init.py:init():517] communicating current version
2021-09-29 17:40:21,648 INFO    MainThread:50058 [wandb_init.py:init():522] got version response 
2021-09-29 17:40:21,648 INFO    MainThread:50058 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-29 17:40:21,822 INFO    MainThread:50058 [wandb_init.py:init():557] starting run threads in backend
2021-09-29 17:40:26,830 INFO    MainThread:50058 [wandb_run.py:_console_start():1605] atexit reg
2021-09-29 17:40:26,831 INFO    MainThread:50058 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-09-29 17:40:26,832 INFO    MainThread:50058 [wandb_run.py:_redirect():1484] Redirecting console.
2021-09-29 17:40:26,839 INFO    MainThread:50058 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-29 17:40:26,840 INFO    MainThread:50058 [wandb_init.py:init():582] run started, returning control to user process
2021-09-29 17:40:43,462 INFO    MainThread:50058 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-29 17:40:43,463 INFO    MainThread:50058 [wandb_run.py:_restore():1547] restore
2021-09-29 17:40:46,387 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-29 17:40:47,563 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-29 17:40:47,718 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-29 17:40:47,888 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 61493
}

2021-09-29 17:40:47,992 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 61902
}

2021-09-29 17:40:48,095 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 61902
  total_bytes: 61902
}

2021-09-29 17:40:48,199 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 61902
  total_bytes: 61902
}

2021-09-29 17:40:48,302 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 61902
  total_bytes: 61902
}

2021-09-29 17:40:48,407 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 61902
  total_bytes: 61902
}

2021-09-29 17:40:48,657 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 61902
  total_bytes: 61902
}

2021-09-29 17:40:48,963 INFO    MainThread:50058 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 61902
  total_bytes: 61902
}
local_info {
}

2021-09-29 17:40:50,634 INFO    MainThread:50058 [wandb_run.py:_show_files():1947] logging synced files
