2021-09-29 17:37:36,074 INFO    MainThread:29664 [wandb_setup.py:_flush():69] setting env: {}
2021-09-29 17:37:36,074 INFO    MainThread:29664 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-29 17:37:36,074 INFO    MainThread:29664 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20210929_173736-2el8b6ty/logs/debug.log
2021-09-29 17:37:36,074 INFO    MainThread:29664 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20210929_173736-2el8b6ty/logs/debug-internal.log
2021-09-29 17:37:36,075 INFO    MainThread:29664 [wandb_init.py:init():381] calling init triggers
2021-09-29 17:37:36,075 INFO    MainThread:29664 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-09-29 17:37:36,075 INFO    MainThread:29664 [wandb_init.py:init():430] starting backend
2021-09-29 17:37:36,075 INFO    MainThread:29664 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-29 17:37:36,083 INFO    MainThread:29664 [backend.py:ensure_launched():135] starting backend process...
2021-09-29 17:37:36,193 INFO    MainThread:29664 [backend.py:ensure_launched():140] started backend process with pid: 33909
2021-09-29 17:37:36,195 INFO    MainThread:29664 [wandb_init.py:init():435] backend started and connected
2021-09-29 17:37:36,198 INFO    MainThread:29664 [wandb_init.py:init():494] updated telemetry
2021-09-29 17:37:36,202 INFO    MainThread:29664 [wandb_init.py:init():517] communicating current version
2021-09-29 17:37:37,627 INFO    MainThread:29664 [wandb_init.py:init():522] got version response 
2021-09-29 17:37:37,627 INFO    MainThread:29664 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-29 17:37:37,815 INFO    MainThread:29664 [wandb_init.py:init():557] starting run threads in backend
2021-09-29 17:37:42,822 INFO    MainThread:29664 [wandb_run.py:_console_start():1605] atexit reg
2021-09-29 17:37:42,823 INFO    MainThread:29664 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-09-29 17:37:42,823 INFO    MainThread:29664 [wandb_run.py:_redirect():1484] Redirecting console.
2021-09-29 17:37:42,866 INFO    MainThread:29664 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-29 17:37:42,866 INFO    MainThread:29664 [wandb_init.py:init():582] run started, returning control to user process
2021-09-29 17:37:59,898 INFO    MainThread:29664 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-29 17:37:59,900 INFO    MainThread:29664 [wandb_run.py:_restore():1547] restore
2021-09-29 17:38:02,410 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-29 17:38:03,327 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-29 17:38:03,503 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-29 17:38:04,210 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-29 17:38:04,316 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 10878
}

2021-09-29 17:38:04,419 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7767
  total_bytes: 10878
}

2021-09-29 17:38:04,524 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10878
  total_bytes: 10878
}

2021-09-29 17:38:04,626 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10878
  total_bytes: 10878
}

2021-09-29 17:38:04,729 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10878
  total_bytes: 10878
}

2021-09-29 17:38:04,832 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10878
  total_bytes: 10878
}

2021-09-29 17:38:05,047 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10878
  total_bytes: 10878
}

2021-09-29 17:38:05,364 INFO    MainThread:29664 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10878
  total_bytes: 10878
}
local_info {
}

2021-09-29 17:38:06,937 INFO    MainThread:29664 [wandb_run.py:_show_files():1947] logging synced files
