2021-11-03 09:01:08,421 INFO    MainThread:83459 [wandb_setup.py:_flush():69] setting env: {}
2021-11-03 09:01:08,421 INFO    MainThread:83459 [wandb_setup.py:_flush():69] setting login settings: {}
2021-11-03 09:01:08,421 INFO    MainThread:83459 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20211103_090108-2qzh0ey6/logs/debug.log
2021-11-03 09:01:08,421 INFO    MainThread:83459 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20211103_090108-2qzh0ey6/logs/debug-internal.log
2021-11-03 09:01:08,422 INFO    MainThread:83459 [wandb_init.py:init():381] calling init triggers
2021-11-03 09:01:08,422 INFO    MainThread:83459 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-11-03 09:01:08,422 INFO    MainThread:83459 [wandb_init.py:init():430] starting backend
2021-11-03 09:01:08,422 INFO    MainThread:83459 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-03 09:01:08,482 INFO    MainThread:83459 [backend.py:ensure_launched():135] starting backend process...
2021-11-03 09:01:08,564 INFO    MainThread:83459 [backend.py:ensure_launched():140] started backend process with pid: 84394
2021-11-03 09:01:08,565 INFO    MainThread:83459 [wandb_init.py:init():435] backend started and connected
2021-11-03 09:01:08,567 INFO    MainThread:83459 [wandb_init.py:init():494] updated telemetry
2021-11-03 09:01:08,568 INFO    MainThread:83459 [wandb_init.py:init():517] communicating current version
2021-11-03 09:01:09,579 INFO    MainThread:83459 [wandb_init.py:init():522] got version response upgrade_message: "wandb version 0.12.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-11-03 09:01:09,580 INFO    MainThread:83459 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-11-03 09:01:09,732 INFO    MainThread:83459 [wandb_init.py:init():557] starting run threads in backend
2021-11-03 09:01:14,739 INFO    MainThread:83459 [wandb_run.py:_console_start():1605] atexit reg
2021-11-03 09:01:14,740 INFO    MainThread:83459 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-11-03 09:01:14,741 INFO    MainThread:83459 [wandb_run.py:_redirect():1484] Redirecting console.
2021-11-03 09:01:14,748 INFO    MainThread:83459 [wandb_run.py:_redirect():1540] Redirects installed.
2021-11-03 09:01:14,749 INFO    MainThread:83459 [wandb_init.py:init():582] run started, returning control to user process
2021-11-03 09:02:10,424 INFO    MainThread:83459 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 1
2021-11-03 09:02:10,425 INFO    MainThread:83459 [wandb_run.py:_restore():1547] restore
2021-11-03 09:02:13,335 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-11-03 09:02:14,056 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-11-03 09:02:14,181 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-11-03 09:02:14,799 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 28605
}

2021-11-03 09:02:14,902 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 28605
}

2021-11-03 09:02:15,004 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28605
  total_bytes: 28605
}

2021-11-03 09:02:15,107 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28605
  total_bytes: 28605
}

2021-11-03 09:02:15,211 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28605
  total_bytes: 28605
}

2021-11-03 09:02:15,314 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28605
  total_bytes: 28605
}

2021-11-03 09:02:15,417 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28605
  total_bytes: 28605
}

2021-11-03 09:02:15,719 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28605
  total_bytes: 28605
}

2021-11-03 09:02:15,996 INFO    MainThread:83459 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28605
  total_bytes: 28605
}
local_info {
}

2021-11-03 09:02:17,341 INFO    MainThread:83459 [wandb_run.py:_show_files():1947] logging synced files
