Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForTokenClassification: ['vocab_transform.weight', 'vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_projector.bias']
- This IS expected if you are initializing DistilBertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    train_loader, val_loader = get_data(PATH, FLAG, AUG, REEXTRACT, FRACTION)
  File "/home/pholur/Situation_Modeling/data.py", line 194, in get_data
    train_dataset = get_data_processed(train_dataset, FLAG)
  File "/home/pholur/Situation_Modeling/data.py", line 83, in get_data_processed
    ordered_posts = list(dataset.keys())
AttributeError: 'NoneType' object has no attribute 'keys'