2021-09-29 17:24:49,666 INFO    MainThread:60145 [wandb_setup.py:_flush():69] setting env: {}
2021-09-29 17:24:49,667 INFO    MainThread:60145 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-29 17:24:49,667 INFO    MainThread:60145 [wandb_init.py:_log_setup():348] Logging user logs to /home/pholur/Situation_Modeling/wandb/run-20210929_172449-1akyvy98/logs/debug.log
2021-09-29 17:24:49,667 INFO    MainThread:60145 [wandb_init.py:_log_setup():349] Logging internal logs to /home/pholur/Situation_Modeling/wandb/run-20210929_172449-1akyvy98/logs/debug-internal.log
2021-09-29 17:24:49,667 INFO    MainThread:60145 [wandb_init.py:init():381] calling init triggers
2021-09-29 17:24:49,667 INFO    MainThread:60145 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {}
2021-09-29 17:24:49,667 INFO    MainThread:60145 [wandb_init.py:init():430] starting backend
2021-09-29 17:24:49,667 INFO    MainThread:60145 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-29 17:24:49,678 INFO    MainThread:60145 [backend.py:ensure_launched():135] starting backend process...
2021-09-29 17:24:49,746 INFO    MainThread:60145 [backend.py:ensure_launched():140] started backend process with pid: 64506
2021-09-29 17:24:49,748 INFO    MainThread:60145 [wandb_init.py:init():435] backend started and connected
2021-09-29 17:24:49,758 INFO    MainThread:60145 [wandb_init.py:init():494] updated telemetry
2021-09-29 17:24:49,759 INFO    MainThread:60145 [wandb_init.py:init():517] communicating current version
2021-09-29 17:24:51,099 INFO    MainThread:60145 [wandb_init.py:init():522] got version response 
2021-09-29 17:24:51,099 INFO    MainThread:60145 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-29 17:24:51,279 INFO    MainThread:60145 [wandb_init.py:init():557] starting run threads in backend
2021-09-29 17:24:56,285 INFO    MainThread:60145 [wandb_run.py:_console_start():1605] atexit reg
2021-09-29 17:24:56,286 INFO    MainThread:60145 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-09-29 17:24:56,286 INFO    MainThread:60145 [wandb_run.py:_redirect():1484] Redirecting console.
2021-09-29 17:24:56,289 INFO    MainThread:60145 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-29 17:24:56,290 INFO    MainThread:60145 [wandb_init.py:init():582] run started, returning control to user process
2021-09-29 17:25:39,274 INFO    MainThread:60145 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 1
2021-09-29 17:25:39,276 INFO    MainThread:60145 [wandb_run.py:_restore():1547] restore
2021-09-29 17:25:41,830 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-29 17:25:43,701 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-29 17:25:43,844 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-09-29 17:25:44,374 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 12281
}

2021-09-29 17:25:44,478 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 12281
}

2021-09-29 17:25:44,581 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 12281
}

2021-09-29 17:25:44,684 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12281
  total_bytes: 12281
}

2021-09-29 17:25:44,786 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12281
  total_bytes: 12281
}

2021-09-29 17:25:44,889 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12281
  total_bytes: 12281
}

2021-09-29 17:25:44,991 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12281
  total_bytes: 12281
}

2021-09-29 17:25:45,095 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12281
  total_bytes: 12281
}

2021-09-29 17:25:45,198 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12281
  total_bytes: 12281
}

2021-09-29 17:25:45,402 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12281
  total_bytes: 12281
}

2021-09-29 17:25:45,682 INFO    MainThread:60145 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12281
  total_bytes: 12281
}
local_info {
}

2021-09-29 17:25:47,238 INFO    MainThread:60145 [wandb_run.py:_show_files():1947] logging synced files
